name: sale-points-service
services:
  postgres:
    image: chainguard/postgres:latest
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    tty: true
    stdin_open: true
